version: '3.9'

services:
  retenciones-service:
    image: retenciones-service
    ports:
      - 8080:8080
      - 5071:5005
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=retenciones2022
      - POSTGRES_USER=postgres
      - POSTGRES_DB=retenciones

networks:
  default:
    name: retenciones_network